GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-type: application/json

{
    "firstName": "John", 
    "lastName": "Smith",
    "email": "email@domain.com",
    "userName": "username",
    "password": "password",
    "identity": "Student"
}

###

POST http://localhost:3000/users/login
Content-type: application/json

{
    "userName": "usernamed",
    "password": "password"
}